server {
    listen 80;

    location / {
        # Uncomment when production:
        #root /usr/share/nginx/html;
        #index index.html;
        #try_files $uri $uri/ /index.html;

        # Delete when production:
        proxy_pass http://frontend:5173/;
    }

    location /api/ {
        proxy_set_header Host $host;
        proxy_pass http://backend:5000/;
    }
}